Wsei.Lab3/Entities/ChatMessageEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Wsei.Lab3.Entities
{
    public class ChatMessageEntity
    {
        public string Username { get; set; }

        public string Content { get; set; }
    }
}

Wsei.Lab3/Entities/ProductEntity.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Wsei.Lab3.Entities
{
    public class ProductEntity
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public bool IsVisible { get; set; }

        public IdentityUser Owner { get; set; }
    }
}

Wsei.Lab3/Models/ErrorViewModel.cs
using System;

namespace Wsei.Lab3.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Wsei.Lab3/Models/ProductModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Wsei.Lab3.Models
{
    public class ProductModel
    {
        public string Name { get; set; }

        public string Description { get; set; }

        public bool IsVisible { get; set; }
    }
}

Wsei.Lab3/Models/ProductStatsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Wsei.Lab3.Models
{
    public class ProductStatsViewModel
    {
        public int NameLength { get; set; }

        public int DescriptionLength { get; set; }
    }
}

Wsei.Lab3/Controllers/ChatController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Wsei.Lab3.Services;

namespace Wsei.Lab3.Controllers
{
    [Authorize]
    public class ChatController : Controller
    {
        public IActionResult Index([FromServices] IChatMessagesRepository repository)
        {
            var messages = repository.GetAll();
            return View(messages);
        }
    }
}

Wsei.Lab3/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Wsei.Lab3.Models;

namespace Wsei.Lab3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Wsei.Lab3/Controllers/MetricsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Wsei.Lab3.Services;

namespace Wsei.Lab3.Controllers
{
    public class MetricsController : Controller
    {
        private readonly IMetricsCollector _collector;

        public MetricsController(IMetricsCollector collector)
        {
            _collector = collector;
        }

        public IActionResult Index()
        {
            var stats = _collector.GetEndpointStats();
            return View(stats);
        }
    }
}

Wsei.Lab3/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Wsei.Lab3.Database;
using Wsei.Lab3.Entities;
using Wsei.Lab3.Models;
using Wsei.Lab3.Services;

namespace Wsei.Lab3.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        private readonly IProductService _productService;

        public ProductsController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(ProductModel product)
        {
            await _productService.Add(product);

            var viewModel = new ProductStatsViewModel
            {
                NameLength = product.Name.Length,
                DescriptionLength = product.Description.Length,
            };

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> List(string name)
        {
            var products = await _productService.GetAll(name);
            return View(products);
        }
    }
}

Wsei.Lab3/Views/Chat/Index.cshtml
@model IEnumerable<Wsei.Lab3.Entities.ChatMessageEntity>

<h1>Global chat</h1>

<div class="d-flex flex-column h-100">
    <div class="flex-grow-1 card mb-1">
        <div class="card-body p-2 overflow-auto" id="messages" style="max-height: 30rem">
            @foreach (var message in Model)
            {
                <div class="p-2">@message.Username says: @message.Content</div>
            }
        </div>
    </div>
    <div class="flex-grow-0">
        <form class="form-inline" id="message-form">
            <div class="input-group w-100">
                <input type="text" class="form-control" name="message" autocomplete="off" />
                <div class="input-group-append">
                    <button type="submit" class="btn btn-info">Send</button>
                </div>
            </div>
        </form>
    </div>
</div>

<script src="~/lib/aspnet-signalr/signalr.js"></script>
<script src="~/js/chat.js"></script>

Wsei.Lab3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<form method="post">
    <button class="btn btn-danger" type="submit">Push me</button>
</form>

Wsei.Lab3/Views/Metrics/Index.cshtml
@model IEnumerable<Wsei.Lab3.Services.EndpointStats>

<h2>Application metrics</h2>

<table class="table">
    <thead>
        <tr>
            <th>HTTP method</th>
            <th>Path</th>
            <th>Request count</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var stats in Model)
        {
            <tr>
                <td>@stats.HttpMethod</td>
                <td>@stats.RequestUrl</td>
                <td>@stats.RequestsCount</td>
            </tr>
        }
    </tbody>
</table>

Wsei.Lab3/Views/Products/Add.cshtml
@model ProductStatsViewModel

<h1>Product added successfully</h1>

<div>Name length: @Model.NameLength</div>
<div>Description length: @Model.DescriptionLength</div>

Wsei.Lab3/Views/Products/Index.cshtml
@model ProductModel

<h1>Add new Product form</h1>

<alert color="success">This is my new alert</alert>

<form method="POST" asp-action="Add">
    <div class="form-group">
        <label asp-for="Name">Item name</label>
        <input asp-for="Name" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Description">Description</label>
        <input asp-for="Description" class="form-control" />
    </div>

    <div class="form-check">
        <input asp-for="IsVisible" class="form-check-input" />
        <label asp-for="IsVisible" class="form-check-label">Item visible?</label>
    </div>

    <div class="form-group">
        <input type="submit" value="Add new item" />
    </div>
</form>

Wsei.Lab3/Views/Products/List.cshtml
@model IEnumerable<Wsei.Lab3.Entities.ProductEntity>

<h2>List of products</h2>

<form method="GET" class="form-inline mb-2">
    <input type="text" name="name" placeholder="Filter by name" class="form-control" />
    <button type="submit" class="btn btn-primary ml-2">Search</button>
</form>

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Is visible?</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.Description</td>
                <td>@(item.IsVisible ? "Yes" : "No")</td>
            </tr>
        }
    </tbody>
</table>

Wsei.Lab3/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Wsei.Lab3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Wsei.Lab3</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Products" asp-action="Index">Add new product</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Products" asp-action="List">List of products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Chat" asp-action="Index">Chat</a>
                            </li>
                        }
                    </ul>

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Wsei.Lab3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Wsei.Lab3/Views/Shared/_MyCustomLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <h1>This is my new application</h1>
    <div>
        @RenderBody()
    </div>
</body>
</html>

Wsei.Lab3/Views/Shared/_MyCustomPartialView.cshtml
@model string

<div>Hello from my partial view!</div>
<div>The string value passed is: '@Model'</div>
<hr />